-- ==============================================================================
-- Script DDL: Criação e Povoamento do Banco de Dados Oracle (Clyvo Vet)
-- ==============================================================================
-- Este script cria as tabelas principais (CORE) da aplicação compatíveis
-- com as entidades tb_users e tb_pets definidas no Entity Framework.

-- ------------------------------------------------------------------------------
-- TABELA: tb_users
-- Descrição: Armazena os dados dos clientes (tutores) da clínica veterinária.
-- ------------------------------------------------------------------------------
CREATE TABLE tb_users (
    -- Identificador único do usuário (Chave Primária com auto-incremento)
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Nome completo do tutor
    Name VARCHAR2(150) NOT NULL,
    -- E-mail para comunicação
    Email VARCHAR2(100) NOT NULL,
    -- Senha de acesso
    Password VARCHAR2(255) NOT NULL,
    -- CPF do tutor
    Cpf VARCHAR2(11) NOT NULL,
    -- Telefone de contato
    Phone VARCHAR2(20) NOT NULL
);

-- ------------------------------------------------------------------------------
-- TABELA: tb_pets
-- Descrição: Armazena os dados dos animais vinculados aos usuários (tutores).
-- ------------------------------------------------------------------------------
CREATE TABLE tb_pets (
    -- Identificador único do pet (Chave Primária)
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Identificador do tutor dono do pet (Chave Estrangeira)
    UserId NUMBER NOT NULL,
    -- Nome do animal
    Name VARCHAR2(100) NOT NULL,
    -- Espécie do animal (ex: Cachorro, Gato)
    Species VARCHAR2(50) NOT NULL,
    -- Raça do animal
    Breed VARCHAR2(50),
    -- Idade do pet
    Age NUMBER(3) NOT NULL,
    -- Peso do pet
    Weight NUMBER(5,2) NOT NULL,
    -- Enums mapeados (Tipo de idade e Tamanho)
    AgeType NUMBER(1) NOT NULL,
    PetSize NUMBER(1) NOT NULL,
    -- Restrição de chave estrangeira
    CONSTRAINT FK_Pet_User FOREIGN KEY (UserId) REFERENCES tb_users(Id) ON DELETE CASCADE
);

-- ==============================================================================
-- DML: Inserção de Dados Significativos (Mínimo de 2 registros por tabela)
-- ==============================================================================

INSERT INTO tb_users (Name, Email, Password, Cpf, Phone) 
VALUES ('Carlos Silva', 'carlos@email.com', 'senha123', '12345678901', '11999999999');

INSERT INTO tb_users (Name, Email, Password, Cpf, Phone) 
VALUES ('Ana Souza', 'ana@email.com', 'senha456', '10987654321', '11888888888');

-- Inserindo Pets e vinculando aos IDs 1 e 2 gerados acima
INSERT INTO tb_pets (UserId, Name, Species, Breed, Age, Weight, AgeType, PetSize) 
VALUES (1, 'Rex', 'Cachorro', 'Labrador', 3, 25.5, 1, 2);

INSERT INTO tb_pets (UserId, Name, Species, Breed, Age, Weight, AgeType, PetSize) 
VALUES (2, 'Mimi', 'Gato', 'Siames', 1, 4.2, 1, 1);